name: 🔂 Unit tests

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
        - "example/**"
        - "README.md"


jobs:
  unit-tests:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        run: python -m pip install -U pdm

      - name: Install dependencies
        run: pdm install

      - name: Run Tests
        run: pdm run pytest -n auto --cov=strawberry_wagtail --cov-report=xml -n auto --showlocals -vv tests

      - uses: codecov/codecov-action@v3
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
